## <span style="color:darkblue"> Class Review </span>

<font size="5"> 

- **Module 1:**

    1. Introduction to GitHub 
    2. Local computing vs. cloud computing 
    3. Local workflows: Anaconda virtual machines and local folders + GitHub desktop 
    4. Cloud workflows: AWS Notebooks + GitHub

<span style="color:white">'</span>
- **Module 2:**

    1. Numbers, arithmetic and numpy math functions
    2. Lists and numpy arrays: storing sequences of data
    3. For loops

## <span style="color:darkblue"> Today: If statement- if-elif-else and **quiz** </span>

<font size="5"> 

- Introduce boolean data type

- Understand if-elif-else statements 

- **Next class:** if-elif-else + while loop + break + class exercises

## <span style="color:darkblue"> Boolean data type </span>

From w3schools

<font size="5"> 

- In programming we often need to know if some expression is ```True``` or ```False```

- We can evaluate **any** expression in Python, and get one of two answers, ```True``` or ```False```

- When you compare two values, the expression is evaluated and Python returns the **Boolean** answer:

**Examples**

In [1]:
print(10 > 9)
print(10 == 9)
print(10 < 9)

True
False
False


In [2]:
type(10 > 9)

bool

## <span style="color:darkblue"> If statement: if-elif-else </span>

<font size="5"> 

- We can use the boolean data type to define if-else statements

- **Importance:** decision making requires the ability to execute a code only if a certain condition is satisfied

<font size="5"> 

**If statement: Python Syntax**

``` python
    if test expression:
        statement(s)
```

![if](images/if.png)

In [8]:
x = '5'
if type(x) == int:
    print(x)

print('hello world')

hello world


In [12]:
import numpy as np
numbers = np.zeros(5)

In [13]:
numbers

array([0., 0., 0., 0., 0.])

In [14]:
import numpy as np

numbers = np.zeros(5)
for i in range(10):
    if i < 5:
        numbers[i] = i


In [15]:
numbers

array([0., 1., 2., 3., 4.])

<font size="5"> 

**If-else statement: Python Syntax**

``` python
    if test expression:
        Body of if
    else:
        Body of else
```

![ifelse](images/ifelse.png)

In [17]:
x = '5'
if type(x) == int:
    print(x)
else:
    print('x is not an integer')

x is not an integer


In [18]:
import numpy as np

numbers = np.zeros(5)
for i in range(10):
    if i < 5:
        numbers[i] = i
    else:
        print(i, 'is not saved into the array')


5 is not saved into the array
6 is not saved into the array
7 is not saved into the array
8 is not saved into the array
9 is not saved into the array


In [19]:
numbers

array([0., 1., 2., 3., 4.])

<font size="5"> 

**If-elif-else statement: Python Syntax**

``` python
    if test expression:
        Body of if
    elif test expression:
        Body of elif
    else: 
        Body of else
```

![elif](images/elif.png)

In [20]:
lista = [1, 1.4, 'f']
int_list = []
float_list = []
str_list = []

for values in lista:
    if type(values)==int:
        int_list.append(values)
    elif type(values)==float:
        float_list.append(values)
    else:
        str_list.append(values)

In [22]:
float_list

[1.4]