## <span style="color:darkblue"> Class Review </span>

<font size="5"> 

- We talked about **lists** and **for loops**

- We covered list methods and explained the structure and meaning of a for loop

- **Questions?**

## <span style="color:darkblue"> Today: arrays, more for loops example and quiz simulation (extra points) </span>

<font size="5"> 

**Learning Objectives:**

- What are arrays? What are the main differences before lists and arrays

- Use list and arrays to store the results of for loop tasks

**During the last 15 minutes of class**

- Accept, clone, solve and push a quiz 

- You can talk and ask questions to each other 

- I will grade the quizzes. Students with 100% of correct answers get +2 points in any quiz they choose

## <span style="color:darkblue"> Arrays </span>

<font size="5"> 

- We’ve already seen that the **Numpy** library provides math functions (for example ```np.exp()``` and ```np.log()```) 

- **Numpy** also provides a type of sequence call **array**

- You can create a new array with the ```np.array``` function, starting with a list 

<font size="5"> 

**Example:**

![prices](images/prices.png)

In [5]:
name_list = [
    'Lobster roll',
    'Chicken caesar',
    'Bang bang chicken',
    'Ham and cheese',
    'Tuna and cucumber',
    'Egg'
]

boston_price_list = [9.99, 7.99, 7.49, 7.00, 6.29, 4.99]
london_price_list = [7.5, 5, 4.4, 5, 3.75, 2.25]

<font size="5"> 

Let's create an array containing Boston prices

In [8]:
import numpy as np

np.array(boston_price_list)

array([9.99, 7.99, 7.49, 7.  , 6.29, 4.99])

dtype('float64')

<font size="5"> 

We can also create arrays without **explicitly** defining a list before

<font size="5"> 

Numpy arrays are in general ```numpy.ndarray```

<font size="5"> 

- The "nd" stands for "n-dimensional", which indicates that NumPy arrays can have any number of dimensions. But for now we will work with one-dimensional sequences

- You can also display the "data type" of the array, which is the type of the elements:

<font size="5"> 

Here is an example of an array with only strings

<font size="5"> 

The main **difference** between an array and a list is that arrays **cannot** store sequences of mixed types 

<font size="5"> 

**Exercise:**

1. Create three ```np.arrays``` with the sandwich prices for London, Boston and Atlanta (I made up the numbers for Atlanta)

    ```atlanta_price_list = [5.5, 2, 2.4, 6, 1.75, 3.25]```

2. Calculate the standard deviations for the sandwich prices in the three cities. Which city has the prices with the lowest standard deviation?

In [15]:
import numpy as np
boston_price_list = [9.99, 7.99, 7.49, 7.00, 6.29, 4.99]
london_price_list = [7.5, 5, 4.4, 5, 3.75, 2.25]
atlanta_price_list = [5.5, 2, 2.4, 6, 1.75, 3.25]

array_boston = np.array(boston_price_list)
array_london = np.array(london_price_list)
array_atlanta = np.array(atlanta_price_list)

In [18]:
prices = [array_boston, array_london, array_atlanta]

In [32]:
prices[0]

array([9.99, 7.99, 7.49, 7.  , 6.29, 4.99])

In [24]:
len(prices)

3

In [34]:
for x in prices:
    print(x)

[9.99 7.99 7.49 7.   6.29 4.99]
[7.5  5.   4.4  5.   3.75 2.25]
[5.5  2.   2.4  6.   1.75 3.25]


In [35]:
len(prices)

3

In [33]:
for x in range(len(prices)):
    print(prices[x])

[9.99 7.99 7.49 7.   6.29 4.99]
[7.5  5.   4.4  5.   3.75 2.25]
[5.5  2.   2.4  6.   1.75 3.25]


In [2]:
stds = []
for price in prices:
    stds.append(np.array(price).std())

In [3]:
stds

[1.5380769017040583, 1.5811388300841898, 1.6749792701868151]